production:
  server: 
    port: 8080
  
  urls: 
    rsybl: "http://192.1.1.15:8280/rSYBL/"  
    store: "http://datastore-research-governify.herokuapp.com/api/v5/"
    mela: "http://192.1.1.15:8180/MELA-AnalysisService/"

  governance:

    service: 
      id: unknown
      unitTh: unknown
      scalable: false

    levels:
      - 'l00'

    elasticitySpeed: {}

    routingSpeed:
      l00: 
        upLevelSpeed: 0.7
        downLevelSpeed: 0.8

    minInstances: {}

  loglevel: info
  logfile: './logs/pro-logs.log'

development:
  server: 
    port: 3000
  
  urls: 
    rsybl: "http://localhost:8280/rSYBL/"  
    store: "http://datastore-research-governify.herokuapp.com/api/v5/"
    mela: "http://localhost:8180/MELA-AnalysisService/"

  governance:

    service: 
      id: unknown
      unitTh: unknown
      scalable: false

    levels:
      - 'l00'

    elasticitySpeed: {}

    routingSpeed:
      l00: 
        upLevelSpeed: 0.7
        downLevelSpeed: 0.8
        
    minInstances: {}

  loglevel: debug
  logfile: './logs/dev-logs.log'


test:
  server: 
    port: 3000
  
  urls: 
    rsybl: "http://192.1.1.15:8280/rSYBL/"  
    store: "http://datastore-research-governify.herokuapp.com/api/v5/"
    mela: "http://192.1.1.15:8180/MELA-AnalysisService/"

  governance:

    service: 
      id: unknown
      unitTh: unknown
      scalable: false

    levels:
      - 'l00'

    elasticitySpeed: {}

    routingSpeed:
      l00: 
        upLevelSpeed: 0.7
        downLevelSpeed: 0.8
        
    minInstances: {}

  loglevel: test
  logfile: './logs/dev-logs.log'