production:
  server: 
    port: 8080

  loglevel: info
  logfile: './logs/pro-logs.log'

development:
  server: 
    port: 3000
    
  loglevel: debug
  logfile: './logs/dev-logs.log'


test:
  server: 
    port: 3000
    
  loglevel: test
  logfile: './logs/dev-logs.log'